kind: Deployment
apiVersion: apps/v1
metadata:
  name: rocketmq-name-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rocketmq-name-service
      name_service_cr: rocketmq-name-service
  template:
    metadata:
      labels:
        app: rocketmq-name-service
        name_service_cr: rocketmq-name-service
    spec:
      volumes:
        - name: rocketmq-namesrv-storage
          persistentVolumeClaim:
            claimName: rocketmq-namesrv-storage
      containers:
        - name: rocketmq-name-service
          image: apacherocketmq/rocketmq:latest
          command:
            - /bin/sh
          args:
            - mqnamesrv
          ports:
            - name: tcp-9876
              containerPort: 9876
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 250m
              memory: 512Mi
          volumeMounts:
            - name: rocketmq-namesrv-storage
              mountPath: /home/rocketmq/logs
              subPath: logs
          imagePullPolicy: Always


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rocketmq-namesrv-storage
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
kind: Service
apiVersion: v1
metadata:
  name: rocketmq-name-server-service
spec:
  ports:
    - name: tcp-9876
      protocol: TCP
      port: 9876
      targetPort: 9876
      nodePort: 30076
  selector:
    name_service_cr: rocketmq-name-service
  type: NodePort