apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: es
  labels:
    app: es
spec:
  serviceName: es
  replicas: 1
  template:
    metadata:
      name: es
      labels:
        app: es
    spec:
      containers:
        - name: es
          image: elasticsearch:8.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            - name: ES_JAVA_OPTS
              value: -Xms256m -Xmx256m
            - name: discovery.type
              value: single-node
      #            - name: xpack.security.http.ssl.enabled
      #              value: 'false'
      #            - name: xpack.security.enrollment.enabled
      #              value: 'true'
      restartPolicy: Always
  selector:
    matchLabels:
      app: es
---
# 修改密码：
# bin/elasticsearch-reset-password --username elastic -i
# 生成 enrollment token
# bin/elasticsearch-create-enrollment-token -s kibana --url "https://localhost:9200"
---
apiVersion: v1
kind: Service
metadata:
  name: es
spec:
  selector:
    app: es
  ports:
    - name: port9200
      port: 9200
      targetPort: 9200
      nodePort: 30200
    - name: port9300
      port: 9300
      targetPort: 9300
      nodePort: 30300
  type: NodePort