apiVersion: v1
kind: Service
metadata:
  name: kibana
spec:
  type: NodePort
  ports:
    - nodePort: 30601
      port: 5601
      protocol: TCP
      targetPort: 5601
  selector:
    run: kibana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: kibana
  name: kibana
spec:
  replicas: 1
  selector:
    matchLabels:
      run: kibana
  strategy: { }
  template:
    metadata:
      labels:
        run: kibana
    spec:
      containers:
        - env:
            - name: discovery.type
              value: single-node
          image: docker.elastic.co/kibana/kibana:8.3.2
          name: kibana
          ports:
            - containerPort: 5601